//
//<?xml version="1.0" encoding="utf-8"?>
//<resources>
//<string name="app_name">LLUJU</string>
//<string name="logintitle">iniciar sesión</string>
//<string name="registered">registrado</string>
//<string name="phoneNumber">número de teléfono </string>
//<string name="password">contraseña</string>
//<string name="forgetpassword">¿olvidaste la contraseña? </string>
//<string name="login">iniciar sesión</string>
//<string name="userAgreement">Inicie sesión para leer y aceptar el</string>
//<string name="Agreement"> acuerdo de usuario</string>
//<string name="codes">código de verificación</string>
//<string name="sendYzCode">código de verificación</string>
//<string name="mailbox">buzón</string>
//<string name="Sharecode">Compartir código</string>
//<string name="registeredTop">Nota: Artículos marcados con</string>
//<string name="registeredTops">son requeridos</string>
//<string name="Registered">Registrado</string>
//<string name="nearbyList">Encuentra negocios cercanos</string>
//<string name="scanRent">escanea el código de alquiler</string>
//<string name="shareCode">Mi código compartido</string>
//<string name="feedback">Pregunta o comentario</string>
//<string name="aboutUs">sobre nosotros</string>
//<string name="userAgreements">Acuerdo de Usuario</string>
//<string name="privacyAgreement">Acuerdo de privacidad</string>
//<string name="balance">Saldo de la cuenta</string>
//<string name="View">Ver</string>
//<string name="logOut">Cerrar sesión</string>
//<string name="rentalRecords">Registros de alquiler</string>
//<string name="cooperation">Cooperación</string>
//<string name="useTutorial">Usar tutorial</string>
//<string name="helpCenter">Centro de ayuda</string>
//<string name="nearbyOutlets">Negocios cercanos</string>
//<string name="shopDetail">Detalle de la tienda</string>
//<string name="retrievePassword">Recuperar Contraseña</string>
//<string name="determine">determinar</string>
//<string name="openingHours">Horario de apertura:</string>
//<string name="address">dirección:</string>
//<string name="phone">teléfono:</string>
//<string name="merchantDescription">Descripción del comerciante:</string>
//<string name="positioningFailed">No podemos ubicar tu posición</string>
//<string name="rules">Reglas de carga</string>
//<string name="billingRules">Reglas de facturación:</string>
//<string name="rentImmediately">Acepta y alquila de inmediato</string>
//<string name="leaseFailed">Renta fallida</string>
//<string name="treasurfailed"> Cargando valor \n no pudo expulsarse </string>
//<string name="nearbyBusinesses">Negocios cercanos</string>
//<string name="customerService">Servicio\n al cliente</string>
//<string name="Tips">Tips</string>
//<string name="phones">Teléfono:</string>
//<string name="workingHours">Horas Laborales:</string>
//<string name="call">llamada</string>
//<string name="personalInformation">Informacion personal</string>
//<string name="avatar">Avatar</string>
//<string name="nickname">Apodo</string>
//<string name="PhoneNumber">Número de teléfono</string>
//<string name="Email">Email</string>
//<string name="takePicture">Toma una foto</string>
//<string name="album">Seleccionar de la galería</string>
//<string name="nicknameTip">Por favor escribe un apodo</string>
//<string name="nicknameTips">Es más fácil para tus amigos encontrarte \n después de configurar tu apodo.</string>
//<string name="Determine">DETERMINAR</string>
//<string name="Eamils">Por favor, introduzca su dirección de correo electrónico</string>
//<string name="Bind">Enlazar</string>
//<string name="Mypurse">Mi monedero</string>
//<string name="details">Detalles de la transacción</string>
//<string name="AccountBalance">Saldo de la cuenta</string>
//<string name="Recharge">Recargar</string>
//<string name="RechargeTip">Saldo de la cuenta corriente</string>
//<string name="payTypeTip">Por favor seleccione el modo de pago</string>
//<string name="payType">Visa / Master Card</string>
//<string name="total">total:</string>
//<string name="Expenses">Registro de gastos</string>
//<string name="selectTime">Por favor seleccione una hora</string>
//<string name="BillingDetails">Detalles de facturación</string>
//<string name="TopUpTobalance">Recargar para el saldo</string>
//<string name="CurrentStatus">Estado actual</string>
//<string name="RechargeTime">Tiempo de recarga</string>
//<string name="paymentMethod">método de pago</string>
//<string name="cardNumber">número de tarjeta </string>
//<string name="TransactionNumber">Número de transacción</string>
//<string name="RentalConsumption">Consumo de renta</string>
//<string name="RechargeSuccessful">Recarga exitosa</string>
//<string name="UseTutorial">Usar tutorial</string>
//<string name="OrderStatus">Estado del pedido</string>
//<string name="Returned">Devuelto</string>
//<string name="OrderNumber">Número de orden:</string>
//<string name="RentalTime">Tiempo de renta: </string>
//<string name="RentalBusiness">Negocio de renta: </string>
//
//<string name="RentalTimes">Tiempos de renta:</string>
//<string name="ReturnTimes">Hora de retorno:</string>
//<string name="LeaseDuration">Duración de la renta:</string>
//<string name="Charges">Cargos:</string>
//<string name="FreeDuration">Duración gratis:</string>
//<string name="EquipmentType">Tipo de equipo:</string>
//<string name="ReturnBusiness">Negocio de retorno:</string>
//<string name="RentalAddress">dirección del negocio:</string>
//<string name="ReturnAddress">dirección de retorno:</string>
//<string name="RentalFees">Tarifas de renta:</string>
//<string name="LostPurchase">Compra perdida</string>
//<string name="orderDetails">Detalles del pedido</string>
//<string name="LostTips">Descripción</string>
//<string name="LostTip">Si el cargador se pierde durante el proceso de renta, \ n puede hacer clic en el botón de compra perdida a continuación. \ n El sistema reembolsará el depósito restante \ n después de deducir el costo del cargador.</string>
//<string name="buy">COMPRAR</string>
//<string name="RentalRecords">Registros de renta</string>
//<string name="cooperationTip"> Está dispuesto a cooperar con usted para una situación beneficiosa para todos y crear posibilidades ilimitadas para el futuro</string>
//
//<string name="shopName">Nombre de tienda </string>
//<string name="shopNameTip">Por favor, introduzca el nombre de una tienda </string>
//<string name="ContactPerson">Persona de contacto </string>
//<string name="ContactPersonTip">Por favor ingrese un contacto </string>
//<string name="phoneTle">telefono </string>
//<string name="phoneTleTip">Por favor, introduzca su número de teléfono  </string>
//<string name="CooperativeContents">contenidos cooperativos </string>
//<string name="CooperativeContentsTip">Ingrese la información con la que desea cooperar</string>
//<string name="MyShareCode">Mi código compartido</string>
//<string name="InvitationCode">Mi codigo de invitacion </string>
//<string name="copy">Copiar</string>
//<string name="copayTip">
//Copie el código de invitación e invite a más amigos a unirse a nosotros. La persona compartida utilizará el código compartido para registrarse y recargar el saldo de la primera cuenta con éxito. El participante y la persona compartida pueden obtener una recompensa de </string>
//
//<string name="copayTips">al mismo tiempo</string>
//<string name="downloadApp">Escanee el código  descargue la APP</string>
//<string name="DeviceID">ID del dispositivo</string>
//<string name="feedbackType">Por favor seleccione el tipo de comentario</string>
//<string name="aboutus">Sobre nosotros</string>
//
//<string name="CustomerHotline">Línea de atención al cliente</string>
//<string name="Emails">E-mail</string>
//<string name="CompanyWebsite">Página Web de la compañía</string>
//<string name="currentVersion">versión actual</string>
//<string name="phoneNumberTip">Por favor ingrese el número de teléfono</string>
//<string name="VerificationCodeTip">por favor ingrese el código de verificación</string>
//<string name="passwordTip">Por favor introduzca la contraseña</string>
//<string name="yourEmail">por favor ingrese su correo electrónico</string>
//<string name="AreaCode">Codigo de Area</string>
//<string name="resend">Reenviar</string>
//<string name="noData">No se encontraron datos</string>
//<string name="noCamera">Imposible usar la cámara</string>
//<string name="acquisitionFailed">La adquisición de datos falló</string>
//<string name="possible">Ingrese su pregunta aquí, disculpe la mala experiencia, nos pondremos en contacto con usted lo antes posible</string>
//<string name="noDeviceId">Por favor ingrese el número de dispositivo</string>
//<string name="noCommonType">Por favor seleccione un tipo de pregunta</string>
//<string name="noEamil">Por favor, introduzca una descripción del problema</string>
//<string name="mobileNumber">Número de teléfono móvil</string>
//<string name="Time">Página Web de la compañía</string>
//<string name="versionNumber">Versión actual</string>
//<string name="cancel">Cancelar</string>
//<string name="loginOut">¿Estás seguro de cerrar sesión?</string>
//<string name="Available">Disponible</string>
//<string name="Rrturn">Puede volver</string>
//<string name="Distance">Distancia</string>
//<string name="noGoogleMap">no puedo encontrar mapas de Google</string>
//<string name="determines">Determinar</string>
//<string name="noDatas">No hay negocios cerca, mira en otros lugares ~</string>
//<string-array name="chinese_week_string_array">
//<item>día</item>
//<item>Uno</item>
//<item>dos</item>
//<item>tres</item>
//<item>cuatro</item>
//<item>cinco</item>
//<item>seis</item>
//</string-array>
//<string name="CreditCard">Tarjeta de crédito</string>
//<string name="CardNumber">Número de tarjeta</string>
//<string name="expirationDate">Fecha de caducidad</string>
//<string name="SecurityCode">Código de seguridad</string>
//<string name="creditCardDetails">Detalles de la tarjeta de crédito</string>
//<string name="creditCardDetailsTip">
//Para desvincular una tarjeta de crédito, simplemente haga clic en el botón de desvinculación
//arriba a la derecha de la página, y vuelva a vincular si es necesario.</string>
//<string name="AddCreditCard">Agregar tarjeta de crédito</string>
//<string name="cardNumberTip">Por favor ingrese el número de tarjeta</string>
//<string name="validityTip">Por favor, introduzca un período de validez</string>
//<string name="securityTip">Por favor introduzca el código de seguridad </string>
//<string name="Cardholder">Nombre del\n tarjetahabiente</string>
//<string name="expirationDateTip">Fecha de caducidad（MM/YY）</string>
//<string name="confirm">Confirmar</string>
//<string name="confirms">CONFIRMAR</string>
//<string name="deleteTips"> ¿Estás seguro de que deseas eliminar la tarjeta de crédito?</string>
//<string name="cardholder">Por favor, introduzca el nombre del titular de la tarjeta</string>
//<string name="validityTypeTip">Período de validez errado</string>
//<string name="noInternet">Tu dispositivo no está conectado</string>
//
//<string name="EamilsTip">Por favor, introduzca su dirección de correo electrónico</string>
//<string name="nocard">Sin enlace de tarjeta de crédito</string>
//<string name="moenys">$</string>
//
//<string name="LeaseTip">Debe vincular una tarjeta de crédito antes de poder alquilar.</string>
//<string name="paytype">Por favor seleccione la tarjeta de pago</string>
//<string name="moneyId">Por favor seleccione la cantidad de recarga</string>
//<string name="payment">Por favor seleccione el modo de pago</string>
//<string name="distance">distancia</string>
//<string name="pwdTip">La contraseña debe tener al menos seis caracteres</string>
//<string name="failedTip">Lo sentimos, tu saldo no se pudo recargar</string>
//<string name="failedTips">Si tiene dudas, comuníquese con el servicio al cliente en línea</string>
//<string name="CustomerService">Servicio al Cliente</string>
//<string name="Rentalsuccess">Renta exitosa</string>
//<string name="Succeeded">El valor de carga \n aparece con éxito</string>
//<string name="contentTip">Por favor complete el contenido de cooperación</string>
//<string name="leaseTips">Por favor, elimine el número</string>
//<string name="leaseTipss">batería, si tienes  </string>
//<string name="leaseTipsss">cualquier pregunta, por favor contacte al servicio al cliente</string>
//<string name="home">Home</string>
//<string name="Deposits">Depósitos</string>
//<string name="FreeDurations">Duración gratis</string>
//<string name="perHour">Cargo por hora</string>
//<string name="dayCap">Día límite</string>
//<string name="TotalCap">Límite total</string>
//<string name="EndOrder">Orden final</string>
//<string name="RefundOfDeposit">Reembolso automático del depósito</string>
//<string name="OFF">OFF</string>
//<string name="OPEN">ABIERTO</string>
//<string name="withDraw">Retirar</string>
//<string name="withDrawTip">Retiro de efectivo actual: 100.00 SAR</string>
//<string name="withDrawalAmount">Cantidad de retiro</string>
//<string name="withdrawAll">Retirar todo</string>
//<string name="withDrawTips">El monto del retiro se devolverá a la cuenta original y se acreditará en 3 a 5 días hábiles</string>
//<string name="withdraw">Retirar >></string>
//<string name="Deposit">Depositar:</string>
//<string name="language">Idioma</string>
//<string name="rent">Rentar</string>
//<string name="revoked">Revocado</string>
//<string name="doubt">Duda</string>
//<string name="purchase">Compra</string>
//<string name="Failure">Fracaso</string>
//<string name="timeout">Se acabó el tiempo</string>
//<string name="payed">Pagado</string>
//<string name="otherCard">Otras tarjetas</string>
//<string name="balanceTip">El saldo de su cuenta actual es</string>
//<string name="balanceTips">, por favor rellene primero</string>
//<string name="depositsTip">Su depósito actual es</string>
//<string name="visa">VISA Tarjeta de crédito</string>
//<string name="Maestro">MAESTRO Tarjeta de crédito</string>
//<string name="jcb">JCB Tarjeta de crédito</string>
//<string name="delectTip">Deslice hacia la izquierda para desligar la tarjeta de crédito.</string>
//<string name="leseTip">El monto de recarga no puede ser menor que el monto de la deuda</string>
//<string name="scanTip">Ya ha alquilado el powerbank, devuelva primero el powerbank</string>
//<string name="RefreshSuccessfully">Actualizar con éxito</string>
//<string name="RechargeDeposit">Depósito de recarga</string>
//<string name="RechargeBalance">Saldo de recarga</string>
//<string name="unpaid">No pagado</string>
//<string name="PaymentFailed">Pago fallido</string>
//<string name="Request">Solicitud</string>
//<string name="successfullyDeleted">borrado exitosamente</string>
//<string name="mailboxs">email</string>
//<string name="eamilTip">por favor ingrese su correo electrónico</string>
//<string name="incorrect">El formato del correo electrónico es incorrecto</string>
//
//
//<string name="OrderConsumption">Consumo de pedidos</string>
//<string name="BackgroundChange">Cambio de fondo</string>
//<string name="WithdrawalBalance">Saldo de retiro</string>
//<string name="WithdrawalDeposit">Depósito de Retiro</string>
//<string name="DeductionBalance">Saldo de deducción</string>
//<string name="success">Completado con éxito</string>
//<string name="paid">A pagar</string>
//<string name="CurrentTotal">Depósito total actual:</string>
//<string name="WithdrawableDeposit">Depósito extraíble:</string>
//<string name="InsufficientDeposit">depósito insuficiente</string>
//<string name="addfailed">La red está ocupada, intente nuevamente</string>
//<string name="addCardTip">Aún no tiene una tarjeta bancaria, ¿desea agregarla?</string>
//<string name="SecurityTip">Por favor introduzca el código de seguridad</string>
//<string name="Securitys">Complete su código PIN, su privacidad \n está segura con LLUJU.</string>
//<string name="identificationNumbers">Por favor, introduzca el número de identificación</string>
//</resources>
